import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Earth Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="google-site-verification" content="qqborC98bnuUS7PLlz7AN_IOBj7uQnr8npL1Up6iTz0" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
